### PR TITLE
Adds GCS provider

### LINKED ISSUE #67: Add support for Google Storage (GCS)
Similar to S3, support GCS as a provider.

https://github.com/variantdev/vals/pull/66

### PR DESCRIPTION
**Pull request by digiserg**
Mimicking S3, this PR adds support for GCS

Resolves #67

### CODE REVIEW

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for your contribution!

I'll try my best to maintain this but as I don't have an immediate access to a GCP account for testing, it would be even more awesome if you could occasionally review issues that may be related to this feature and help me provide user support!

**Comment by mumoshu** [comment]
@digiserg Argh! Would you mind resolving conflicts?

**Comment by digiserg** [comment]
> @digiserg Argh! Would you mind help resolving conflicts?

Done!

**Comment by mumoshu** [comment]
@digiserg Merged. Thanks a lot for your help!

**Pull request merged**
