### PR TITLE
chore: add travis and goreleser

### PR DESCRIPTION
**Pull request by aldor007**
The intention of this commit is to allow to have binary releases of vals tool on Github

But tests aren't passing :(

### CODE REVIEW

**Comment by mumoshu** [comment]
@aldor007 Hey! Thanks for the PR. Just confirming, but why did you remove `pkg/providers/gcpsecrets/gcpsecrets_test.go `?

**Comment by aldor007** [comment]
Hi @mumoshu 

I've removed `pkg/providers/gcpsecrets/gcpsecrets_test.go` because of the cycle that this file is making. 
```
# github.com/variantdev/vals/pkg/providers/gcpsecrets
import cycle not allowed in test
package github.com/variantdev/vals/pkg/providers/gcpsecrets (test)
	imports github.com/variantdev/vals
	imports github.com/variantdev/vals/pkg/providers/gcpsecrets
``` 
https://travis-ci.com/github/aldor007/vals/builds/161295846

I was thinking how to fix it but in this test, I can't see any assertion so IMO it is not checking anything 

Sadly tests aren't passing event after this change 
https://travis-ci.com/github/aldor007/vals/builds/161478400

**Comment by mumoshu** [comment]
Thanks!

For `vals_awssecrets_test.go`, it won't pass without actual AWS credentials. So please feel free to skip it on CI for now.

For Vault-related tests, I thought I had to run a vault devserver for that to pass.

Finally, `pkg/providers/gcpsecrets/gcpsecrets_test.go` seems like an incomplete test that seems to not work at all. Sry for back and forth but please feel free to remove it!

**Comment by mumoshu** [comment]
@aldor007 I've just finished setting up automated binary releases with goreleaser and GitHub Actions. This work has been the source of inspiration for that! Thanks for your contribution.

**Pull request closed without merging**
