### PR TITLE
Update readme according to current Vault version

### PR DESCRIPTION
**Pull request by caseycs**
I tried to make the application work with current vault version, with some debugging efforts I could make it work. Main reason is that examples provided are probably outdated, so here is my PR.

### CODE REVIEW

**Comment by mumoshu** [comment]
@caseycs Hey! Thanks a lot for trying it out and the doc fix.

Honestly saying, I'm not an expert Vault user.

So can I ask you about which Vault backend you used for the `secret/` path?

The former `mykv` in the example was created by mounting - I think - the kv v1 backend.

```
vault secrets enable -path=mykv kv
vault write mykv/foo mykey=myvalue
vault read mykv/foo
```

So, perhaps, we'd better including the `vault secrests enable -path=secrets <whatever backend you used in the example>` in the very beginning of the guide?

**Comment by caseycs** [comment]
There are two few things:
1) secret instead of mykv, with is enabled by default vault engine in dev environment. The fact that it's default makes me think that it's a good idea
2) missing /data part in the url - it's part of new api and without it the tool does not work at all, so for me it's a must to mention in the docs/readmez same as another response format, look at the jq path
3) vault host and port does not work while they are mentioned as described in current readme, env or default values is used instead, so provided examples are very confusing

**Comment by mumoshu** [comment]
Thanks!

> missing /data part in the url - it's part of new api and without it the tool does not work at all

Ah, so would this one of changes in the v2 of the kv backend?

**Comment by mumoshu** [comment]
> vault host and port does not work while they are mentioned as described in current readme, env or default value (localhost) is used instead, so provided examples are very confusing

Correct. `?address=http:/host:port` or `VAULT_ADDR` should be used for that. The doc was outdated here!

**Comment by mumoshu** [comment]
> secret instead of mykv, with is enabled by default vault engine in dev environment

Okay just confirmed that. Now trying to check if this is v1 or v2(I thought `kv` had two versions, but was it my misconception?

```
vault secrets list
Path          Type         Accessor              Description
----          ----         --------              -----------
cubbyhole/    cubbyhole    cubbyhole_b1d0ff84    per-token private secret storage
identity/     identity     identity_6d74ff2b     identity store
secret/       kv           kv_c5ad200d           key/value secret storage
sys/          system       system_6c76756c       system endpoints used for control, policy and debugging
```

**Comment by caseycs** [comment]
This part I do not know, I'm also not a Vault expert
But at least changes I propose work out-of the box against current default vault setup in docker

**Comment by mumoshu** [comment]
@caseycs Understood. Regardless of the v1-or-v2 thing, this looks awesome! Thanks for your contribution ☺️

**Pull request merged**
