### PR TITLE
Add support for Azure Key Vault secrets

### PR DESCRIPTION
**Pull request by tnaroska**
This adds a simple provider for Azure Key Vault as requested in #21

### CODE REVIEW

**Comment by lukasmrtvy** [comment]
Is possible to implenent also MSI authentication ? It will cover indentites and temporary credentials generated from az login

**Comment by tnaroska** [comment]
The code is using auth.NewAuthorizerFromEnvironment() method from Azure SDK:
https://github.com/Azure/azure-sdk-for-go#more-authentication-details
That claims it's supporting MSI automatically:
```
1. **Client Credentials**: Azure AD Application ID and Secret.

    - `AZURE_TENANT_ID`: Specifies the Tenant to which to authenticate.
    - `AZURE_CLIENT_ID`: Specifies the app client ID to use.
    - `AZURE_CLIENT_SECRET`: Specifies the app secret to use.

2. **Client Certificate**: Azure AD Application ID and X.509 Certificate.

    - `AZURE_TENANT_ID`: Specifies the Tenant to which to authenticate.
    - `AZURE_CLIENT_ID`: Specifies the app client ID to use.
    - `AZURE_CERTIFICATE_PATH`: Specifies the certificate Path to use.
    - `AZURE_CERTIFICATE_PASSWORD`: Specifies the certificate password to use.

3. **Resource Owner Password**: Azure AD User and Password. This grant type is *not
   recommended*, use device login instead if you need interactive login.

    - `AZURE_TENANT_ID`: Specifies the Tenant to which to authenticate.
    - `AZURE_CLIENT_ID`: Specifies the app client ID to use.
    - `AZURE_USERNAME`: Specifies the username to use.
    - `AZURE_PASSWORD`: Specifies the password to use.

4. **Azure Managed Service Identity**: Delegate credential management to the
   platform. Requires that code is running in Azure, e.g. on a VM. All
   configuration is handled by Azure. See [Azure Managed Service
   Identity](https://docs.microsoft.com/azure/active-directory/msi-overview)
   for more details.
```

**Comment by lukasmrtvy** [comment]
@mumoshu is possible to merge this? :) thanks

**Review by mumoshu — APPROVED** [review]
Awesome work! Thanks for your contribution @tnaroska ☺️

**Comment by lukasmrtvy** [comment]
@tnaroska Did You try this change? 

1. `az login`
2. `echo 'foo: secretref+azurekeyvault://my-vault/secret-e' | vals eval -f -`
3. hangs forever

even `echo 'foo: secretref+azurekeyvault://nonexistantvault/andsecret' | vals eval -f -` hangs forever.

**Comment by lukasmrtvy** [comment]
Seems that `auth.NewAuthorizerFromCLI()` is needed for that ^ use case..

**Comment by tnaroska** [comment]
@lukasmrtvy yes, the current implementation requires credentials in the environment variables. Unfortunately it doesn't work with simply running `az login`. You'd have to get the tokens and populate the env vars.
Having a way to switch between `auth.NewAuthorizerFromCLI` and `auth.NewAuthorizerFromEnvironment()` would be nice, but as you found there is a lot of different ways for authenticating in azure... I don't know enough details about all the possible auth methods to comfortably implement such a switch. So, I decided to go with `auth.NewAuthorizerFromEnvironment()` since that supports the use case in our automation scripts (with the caveat of making manual testing a little more complicated).

If you think you have a solution, I'm happy to help review and test it.

**Comment by tnaroska** [comment]
I also took a quick look at the terraform implementation. They seem to be using their own azure client lib rather than the official Azure SDK! Go figure.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/provider/provider.go#L9

**Comment by lukasmrtvy** [comment]
@tnaroska here is maybe better example https://github.com/mozilla/sops/blob/master/azkv/keysource.go#L57-L143

**Comment by tnaroska** [comment]
👍 I'll take a look over the weekend

**Comment by tnaroska** [comment]
@lukasmrtvy new PR: https://github.com/variantdev/vals/pull/43

**Pull request merged**
